### ISSUE TITLE
Plugin isn't recognized in 4Dv13.6

### ISSUE THREAD

**Issue by tpenner** [miyako/4d-plugin-pngcrush#1]
It is recognized in 4Dv14.5 and 4Dv15.2

I only tested on Windows 10 (64-bit) using the 32-bit version of 4D mono.

**Comment by miyako** [comment]
did you try the copy inside the "v11" folder? 
v11 means, v11 (Intel) and above, including v14 and v15.

the copy at the top level is for v14 and above, 
which uses a new plugin architecture (no RSR files, manifest.json, no carbon, etc).

**Comment by tpenner** [comment]
I had originally tried the version inside of:
`4d-plugin-pngcrush-master\pngcrush\Pngcrush.4dbase\Plugins\Pngcrush.bundle\`

I just now tried `4d-plugin-pngcrush-master\pngcrush\v11\Pngcrush.4dbase\Plugins\Pngcrush.bundle\` and it works fine with v13.

Thank you.
